### PR TITLE
feat(map): sync map.jinja with template-formula

### PR DESCRIPTION
**Pull request by n-rodriguez**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by noelmcloughlin — APPROVED** [review]
LGTM. This is improved structure like template-formula!!  Thanks @n-rodriguez

**Comment by n-rodriguez** [comment]
@myii ping

**Comment by myii** [comment]
@n-rodriguez I'm almost done with the testing behind this PR.  I'm not sure if you're aware of the new `yaml_dump` => `_mapdata` states that we've been discussing for how to track `map.jinja` changes.  Here are some of the tests I've already gone through (the underlying commits are linked in Travis):

* https://travis-ci.org/github/myii/openntpd-formula/builds/720100767
* https://travis-ci.org/github/myii/openntpd-formula/builds/720250261
* https://travis-ci.org/github/myii/openntpd-formula/builds/720481296

I'll tidy it up and push it through soon, so that we can finalise this PR as well.

**Comment by n-rodriguez** [comment]
>  I'm not sure if you're aware of the new `yaml_dump` => `_mapdata` states that we've been discussing for how to track `map.jinja` changes.

nope

**Comment by myii** [comment]
@n-rodriguez To make things easier, I can just add [the commit](https://github.com/myii/openntpd-formula/commit/60b37e41d731aaf185f9ac66db6ae0a4005c07f8) once the conflict has been resolved.  Do you want me to do that?

**Comment by n-rodriguez** [comment]
@myii rebased

**Comment by n-rodriguez** [comment]
>  Do you want me to do that?

sure

**Comment by myii** [comment]
@n-rodriguez `kitchen.yml` needs this, right?

```diff
-            - openntpd.config
+            - openntpd
```

**Comment by n-rodriguez** [comment]
> @n-rodriguez `kitchen.yml` needs this, right?

fixed

**Comment by myii** [comment]
aec6af0054b9b8fffc81c780849d6704461f7dfa pushed -- will merge if all tests pass.

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
@n-rodriguez Merged, thanks for upgrading this `map.jinja`.  One issue remaining for consideration for `arch-base-latest`:

https://github.com/saltstack-formulas/openntpd-formula/blob/c1dc44f31301e3d75477757094afd9796a5a157f/test/integration/default/files/_mapdata/arch-base-latest.yaml#L10-L14

Are we agreed that we'll just leave that as it is?

**Comment by n-rodriguez** [comment]
> Are we agreed that we'll just leave that as it is?

yes

**Pull request merged**
