### PR TITLE
test(map): verify `map.jinja` dump using `_mapdata` state

### PR DESCRIPTION
**Pull request by myii**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [x] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

* Semi-automated using https://github.com/myii/ssf-formula/pull/244
* Prompted by #7

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by baby-gnu — APPROVED** [review]

**Review by n-rodriguez — APPROVED** [review]

**Comment by myii** [comment]
Thanks for the reviews, @baby-gnu and @n-rodriguez.  If this is merged before #7, then there will be a minor conflict in `kitchen.yml` (where `.config` needs to be removed).  Also, this commit can be used to get the `_mapdata` tests passing:

* https://github.com/myii/openntpd-formula/commit/60b37e41d731aaf185f9ac66db6ae0a4005c07f8
  - Using `test/integration/default/files/_mapdata/arch-base-latest.yaml` as opposed to `test/integration/default/files/_mapdata/arch-5.yaml`

**Comment by myii** [comment]
Note, I've already tested #7 with this and generally all looks fine.  However, it did uncover that the following is being used for Arch Linux as well:

```yaml
  server:
  - address: 0.debian.pool.ntp.org
  - address: 1.debian.pool.ntp.org
  - address: 2.debian.pool.ntp.org
  - address: 3.debian.pool.ntp.org
```

Personally, I don't think this is much of a problem.  However, I also did a quick test using `*.arch.pool.ntp.org` instead:

* https://github.com/myii/openntpd-formula/commit/d0b39e7f0a6917851a2b8d9e189acf42be3bb5d4
  - Anything useful here can be used if desired.

**Comment by myii** [comment]
@n-rodriguez How would you like to proceed?

1. Merge this first, then #7 after rebasing?
1. Merge #7 as-is and modify this PR to adjust to that?

In either case, the Arch Linux testing question still remains, which can be tackled afterwards, if we feel that it's necessary.

**Comment by n-rodriguez** [comment]
> Merge this first, then #7 after rebasing?

**Comment by myii** [comment]
@n-rodriguez Thanks, merged -- over to you!

**Pull request merged**
